name: 빌드 및 배포 

on:
  push:
    branches: [ main ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: 원격저장소에서 소스를 복사
        uses: actions/checkout@v3

      - name: 소스 파일을 docker이미지로 빌드한다
        run: docker build -t moon8sun/my-fastapi-whoami:latest .

      - name: docker hub에 로그인 한다. 
        run: docker login -u moon8sun -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: 생성된 이미지를 docker hub에 푸시한다
        run: docker push moon8sun/my-fastapi-whoami:latest
  
  deploy:
    needs: build-docker-image
    name: deploy
    runs-on: [ self-hosted, label-kosa ]
    steps:
      - name: 기존에 실행중인 서비스를 제거한다. 
        run: docker service rm my-fastapi-whoami-app

      - name: docker hub에 로그인 한다. 
        run: docker login -u moon8sun -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: 생성된 이미지를 docker hub에 pull로 내려 받는다
        run: docker pull moon8sun/my-fastapi-whoami:latest

      - name: 서비스 실행
      - run: |
          docker service create \
          --name my-fastapi-whoami-app \
          --publish published=8000,target=8000 \
          --replicas 3 \
          moon8sun/my-fastapi-whoami
